---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/deploy-worker
    tag: v1.0

run:
  path: pipeline-repo/ci/scripts/generate-manifest.sh

inputs:
- name: pipeline-repo
- name: vault

outputs:
- name: manifest
